using System.Threading.Tasks.Dataflow;

namespace TestConcurrencyControl.TestTPLDataflow
{
    public class TestTPLDataflow
    {
        public static async Task Run()
        {
            var block = new ActionBlock<string>(async item =>
            {
                Console.WriteLine($"任务 {item} 开始执行...");
                await Task.Delay(2000);
                Console.WriteLine($"任务 {item} 执行完成！");
            }, new ExecutionDataflowBlockOptions
            {
                MaxDegreeOfParallelism = 3
            });

            for (int i = 0; i < 20; i++)
            {
                Console.WriteLine($"添加任务 {i + 1} 到队列中...");
                block.Post($"{i + 1}");
            }

            block.Complete();
            await block.Completion;
            Console.WriteLine("所有任务执行完成！");
        }
        /*
           添加任务 1 到队列中...
           添加任务 2 到队列中...
           添加任务 3 到队列中...
           添加任务 4 到队列中...
           添加任务 5 到队列中...
           添加任务 6 到队列中...
           添加任务 7 到队列中...
           添加任务 8 到队列中...
           任务 3 开始执行...
           添加任务 9 到队列中...
           添加任务 10 到队列中...
           添加任务 11 到队列中...
           添加任务 12 到队列中...
           添加任务 13 到队列中...
           添加任务 14 到队列中...
           添加任务 15 到队列中...
           添加任务 16 到队列中...
           添加任务 17 到队列中...
           添加任务 18 到队列中...
           添加任务 19 到队列中...
           添加任务 20 到队列中...
           任务 2 开始执行...
           任务 1 开始执行...
           任务 2 执行完成！
           任务 1 执行完成！
           任务 4 开始执行...
           任务 5 开始执行...
           任务 3 执行完成！
           任务 6 开始执行...
           任务 5 执行完成！
           任务 4 执行完成！
           任务 6 执行完成！
           任务 9 开始执行...
           任务 8 开始执行...
           任务 7 开始执行...
           任务 8 执行完成！
           任务 7 执行完成！
           任务 11 开始执行...
           任务 10 开始执行...
           任务 9 执行完成！
           任务 12 开始执行...
           任务 12 执行完成！
           任务 11 执行完成！
           任务 10 执行完成！
           任务 13 开始执行...
           任务 14 开始执行...
           任务 15 开始执行...
           任务 15 执行完成！
           任务 13 执行完成！
           任务 14 执行完成！
           任务 16 开始执行...
           任务 17 开始执行...
           任务 18 开始执行...
           任务 18 执行完成！
           任务 17 执行完成！
           任务 16 执行完成！
           任务 19 开始执行...
           任务 20 开始执行...
           任务 19 执行完成！
           任务 20 执行完成！
           所有任务执行完成！
         */
    }
}
