namespace TestConcurrencyControl.TestParallelForEach
{
    public class TestParallelForEach
    {
        public static async Task Run()
        {
            ParallelOptions options = new ParallelOptions()
            {
                MaxDegreeOfParallelism = 3
            };
            await Parallel.ForEachAsync(Enumerable.Range(1, 20), options, async (i, c) =>
            {
                Console.WriteLine($"任务 {i} 开始执行...");
                await Task.Delay(2000, c);
                Console.WriteLine($"任务 {i} 执行完成！");
            });
            Console.WriteLine("所有任务执行完成！");
        }

        /*
           任务 2 开始执行...
           任务 1 开始执行...
           任务 3 开始执行...
           任务 1 执行完成！
           任务 3 执行完成！
           任务 2 执行完成！
           任务 4 开始执行...
           任务 5 开始执行...
           任务 6 开始执行...
           任务 6 执行完成！
           任务 5 执行完成！
           任务 4 执行完成！
           任务 7 开始执行...
           任务 8 开始执行...
           任务 9 开始执行...
           任务 9 执行完成！
           任务 10 开始执行...
           任务 8 执行完成！
           任务 7 执行完成！
           任务 12 开始执行...
           任务 11 开始执行...
           任务 12 执行完成！
           任务 13 开始执行...
           任务 10 执行完成！
           任务 14 开始执行...
           任务 11 执行完成！
           任务 15 开始执行...
           任务 13 执行完成！
           任务 15 执行完成！
           任务 14 执行完成！
           任务 16 开始执行...
           任务 17 开始执行...
           任务 18 开始执行...
           任务 16 执行完成！
           任务 18 执行完成！
           任务 17 执行完成！
           任务 19 开始执行...
           任务 20 开始执行...
           任务 19 执行完成！
           任务 20 执行完成！
           任务全部完成！
         */
    }
}
